export const banks = [
  {
    bankId: "252",
    url: "https://www.dnb.no/",
    name: "DNB Bank ASA",
  },
  {
    bankId: "250",
    url: "https://www.handelsbanken.no",
    name: "Handelsbanken AB NUF",
  },
  {
    bankId: "3831530",
    url: "https://www.dnb.no/kundeprogram/avtaler/bonord",
    name: "BONORD (DNB)",
  },
  {
    bankId: "1351017",
    url: "https://www.bulder.no/",
    name: "Bulder (Sparebanken Norge)",
  },
  {
    bankId: "330",
    url: "https://www.jbf.no/",
    name: "JBF Bank og Forsikring",
  },
  {
    bankId: "431",
    url: "https://www.landkredittbank.no",
    name: "Landkreditt Bank AS",
  },
  {
    bankId: "272",
    url: "https://www.esbank.no",
    name: "Marker & Eidsberg Sparebank",
  },
  {
    bankId: "3831529",
    url: "https://www.dnb.no/kundeprogram/avtaler/nobl",
    name: "NOBL (DNB)",
  },
  {
    bankId: "371",
    url: "https://www.nordea.no",
    name: "NORDEA BANK ABP, FILIAL I NORGE",
  },
  {
    bankId: "772261",
    url: "https://www.dnb.no/nsf",
    name: "Norsk Sykepleierforbund (DNB)",
  },
  {
    bankId: "357",
    url: "https://bank.obos.no/",
    name: "OBOS-banken AS",
  },
  {
    bankId: "3861836",
    url: "https://www.penni.no/",
    name: "Penni fra Eika digitalbank",
  },
  {
    bankId: "474",
    url: "https://www.rogalandsparebank.no/",
    name: "Rogaland Sparebank",
  },
  {
    bankId: "285",
    url: "https://www.romsdalsbanken.no/",
    name: "Romsdal Sparebank",
  },
  {
    bankId: "332",
    url: "https://www.sognbank.no/",
    name: "Sogn Sparebank",
  },
  {
    bankId: "345",
    url: "https://www.sparebank1.no/nb/hallingdal/privat.html",
    name: "SpareBank 1 Hallingdal Valdres",
  },
  {
    bankId: "441",
    url: "https://www.sparebank1.no/nb/helgeland/privat.html",
    name: "SpareBank 1 Helgeland",
  },
  {
    bankId: "471",
    url: "https://www.sparebank1.no/nb/lom-skjaak/privat.html",
    name: "SpareBank 1 Lom og Skjåk",
  },
  {
    bankId: "341",
    url: "https://www.sparebank1.no/nb/nord-norge/privat.html",
    name: "SpareBank 1 Nord-Norge",
  },
  {
    bankId: "259",
    url: "https://www.sparebank1.no/nb/nordvest/privat.html",
    name: "SpareBank 1 Nordmøre",
  },
  {
    bankId: "346",
    url: "https://www.sparebank1.no/nb/ringerike-hadeland/privat.html",
    name: "SpareBank 1 Ringerike Hadeland",
  },
  {
    bankId: "342",
    url: "https://www.sparebank1.no/nb/smn/privat.html",
    name: "SpareBank 1 SMN",
  },
  {
    bankId: "340",
    url: "https://www.sparebank1.no/nb/sr-bank/privat.html",
    name: "SpareBank 1 Sør-Norge",
  },
  {
    bankId: "368",
    url: "https://www.sparebank1.no/nb/ostlandet/privat.html",
    name: "SpareBank 1 Østlandet",
  },
  {
    bankId: "422",
    url: "https://www.sbm.no/",
    name: "Sparebanken Møre",
  },
  {
    bankId: "420",
    url: "https://www.oest.no",
    name: "Sparebanken Øst",
  },
  {
    bankId: "277",
    url: "https://www.sunndal-sparebank.no",
    name: "Sunndal Sparebank",
  },
  {
    bankId: "428",
    url: "https://sgsparebank.no/",
    name: "Søgne og Greipstad Sparebank",
  },
  {
    bankId: "306",
    url: "https://tinnbank.no/",
    name: "Tinn Sparebank",
  },
  {
    bankId: "305",
    url: "https://tos.no/",
    name: "Tolga-Os Sparebank",
  },
  {
    bankId: "298",
    url: "https://www.valdressparebank.no/",
    name: "Valdres Sparebank",
  },
  {
    bankId: "297",
    url: "https://vossabanken.no/",
    name: "Voss Sparebank",
  },
  {
    bankId: "352",
    url: "https://www.orskogsparebank.no/",
    name: "Ørskog Sparebank",
  },
  {
    bankId: "253",
    url: "https://www.aasen-sparebank.no",
    name: "Aasen Sparebank",
  },
  {
    bankId: "266",
    url: "https://www.aurskog-sparebank.no/",
    name: "Aurskog Sparebank",
  },
  {
    bankId: "462",
    url: "https://www.fanasparebank.no",
    name: "Fana Sparebank",
  },
  {
    bankId: "370",
    url: "https://www.strommensparebank.no",
    name: "Strømmen Sparebank",
  },
  {
    bankId: "329",
    url: "https://www.nidaros-sparebank.no/",
    name: "Nidaros Sparebank",
  },
  {
    bankId: "376",
    url: "https://luster-sparebank.no/",
    name: "Luster Sparebank",
  },
  {
    bankId: "296648",
    url: "https://skuesparebank.no/",
    name: "Skue Sparebank",
  },
  {
    bankId: "349",
    url: "https://www.rindalsbanken.no/",
    name: "Rindal Sparebank",
  },
  {
    bankId: "347",
    url: "https://www.rorosbanken.no/",
    name: "Rørosbanken Røros Sparebank",
  },
];

export const principalMortgageOffers = [
  {
    id: "1424927",
    bankId: "471",
    name: "LOfavør Førstehjemslån",
    nominalRate: 5.15,
    effectiveRate: 5.3,
    type: "annuitet",
    requireMembership: true,
    requirePackage: false,
    union: "LOFavør",
  },
  {
    id: "3761818",
    bankId: "341",
    name: "LOfavør Grønt Førstehjemslån",
    nominalRate: 5.17,
    effectiveRate: 5.33,
    type: "annuitet",
    requireMembership: true,
    requirePackage: false,
    union: "LOFavør",
  },
  {
    id: "3760440",
    bankId: "342",
    name: "LOfavør Grønt Førstehjemslån",
    nominalRate: 5.19,
    effectiveRate: 5.34,
    type: "annuitet",
    requireMembership: true,
    requirePackage: true,
    union: "LOFavør",
  },
  {
    id: "1421889",
    bankId: "368",
    name: "LOfavør Førstehjemslån",
    nominalRate: 5.19,
    effectiveRate: 5.34,
    type: "annuitet",
    requireMembership: true,
    requirePackage: true,
    union: "LOFavør",
  },
  {
    id: "3790983",
    bankId: "297",
    name: "Fyrsteheimslån",
    nominalRate: 5.19,
    effectiveRate: 5.35,
    type: "annuitet",
    requireMembership: false,
    requirePackage: true,
  },
  {
    id: "3861810",
    bankId: "471",
    name: "LOfavør Grønt Boliglån",
    nominalRate: 5.2,
    effectiveRate: 5.35,
    type: "annuitet",
    requireMembership: true,
    requirePackage: false,
    union: "LOFavør",
  },
  {
    id: "2519783",
    bankId: "471",
    name: "Førstehjemslån for unge",
    nominalRate: 5.2,
    effectiveRate: 5.36,
    type: "annuitet",
    requireMembership: false,
    requirePackage: false,
  },
  {
    id: "1108004",
    bankId: "342",
    name: "LOfavør Førstehjemslån 90 %",
    nominalRate: 5.24,
    effectiveRate: 5.39,
    type: "annuitet",
    requireMembership: true,
    requirePackage: true,
    union: "LOFavør",
  },
  {
    id: "3866967",
    bankId: "272",
    name: "Grønt Boliglån Ung",
    nominalRate: 5.24,
    effectiveRate: 5.4,
    type: "annuitet",
    requireMembership: false,
    requirePackage: true,
  },
  {
    id: "3697820",
    bankId: "420",
    name: "ABBL Boliglån ung",
    nominalRate: 5.24,
    effectiveRate: 5.4,
    type: "annuitet",
    requireMembership: true,
    requirePackage: false,
    union: "ABBL-medlemmer",
  },
  {
    id: "1422328",
    bankId: "346",
    name: "LOfavør Førstehjemslån",
    nominalRate: 5.24,
    effectiveRate: 5.4,
    type: "annuitet",
    requireMembership: true,
    requirePackage: false,
    union: "LOfavør UNG",
  },
  {
    id: "2885377",
    bankId: "349",
    name: "Grønt boliglån ungdom",
    nominalRate: 5.25,
    effectiveRate: 5.41,
    type: "annuitet",
    requireMembership: false,
    requirePackage: true,
  },
  {
    id: "1906426",
    bankId: "332",
    name: "Fyrsteheimslån Ung 18-34 år, Sogn Sparebank",
    nominalRate: 5.25,
    effectiveRate: 5.42,
    type: "annuitet",
    requireMembership: false,
    requirePackage: false,
  },
  {
    id: "3442028",
    bankId: "341",
    name: "Grønt Førstehjemslån",
    nominalRate: 5.26,
    effectiveRate: 5.43,
    type: "annuitet",
    requireMembership: false,
    requirePackage: false,
  },
  {
    id: "3761799",
    bankId: "341",
    name: "LOfavør Grønt Boliglån",
    nominalRate: 5.27,
    effectiveRate: 5.44,
    type: "annuitet",
    requireMembership: true,
    requirePackage: false,
    union: "LOFavør",
  },
  {
    id: "3286553",
    bankId: "420",
    name: "Grønt førstehjemslån",
    nominalRate: 5.28,
    effectiveRate: 5.44,
    type: "annuitet",
    requireMembership: false,
    requirePackage: false,
  },
  {
    id: "1106511",
    bankId: "340",
    name: "LOfavør Førstehjemslån",
    nominalRate: 5.29,
    effectiveRate: 5.45,
    type: "annuitet",
    requireMembership: true,
    requirePackage: true,
    union: "LOfavør UNG, LOFavør",
  },
  {
    id: "2075095",
    bankId: "471",
    name: "Fjellbanken DNT Boliglån UNG",
    nominalRate: 5.29,
    effectiveRate: 5.45,
    type: "annuitet",
    requireMembership: true,
    requirePackage: true,
    union: "Fjellbanken DNT Boliglån",
  },
  {
    id: "630845",
    bankId: "471",
    name: "LOfavør Boliglån Ung",
    nominalRate: 5.29,
    effectiveRate: 5.45,
    type: "annuitet",
    requireMembership: true,
    requirePackage: false,
    union: "LOfavør UNG",
  },
  {
    id: "3839903",
    bankId: "330",
    name: "NJF - Boliglån for unge",
    nominalRate: 5.28,
    effectiveRate: 5.45,
    type: "annuitet",
    requireMembership: true,
    requirePackage: true,
    union: "Norsk Jernbaneforbund",
  },
  {
    id: "3840038",
    bankId: "330",
    name: "NLF - Boliglån for unge",
    nominalRate: 5.28,
    effectiveRate: 5.45,
    type: "annuitet",
    requireMembership: true,
    requirePackage: true,
    union: "Norsk Lokomotivførerforbund",
  },
  {
    id: "3603539",
    bankId: "474",
    name: "Bate - Førstehjemslån",
    nominalRate: 5.29,
    effectiveRate: 5.45,
    type: "annuitet",
    requireMembership: true,
    requirePackage: true,
    union: "Bate",
  },
  {
    id: "3360767",
    bankId: "376",
    name: "Førsteheimslån",
    nominalRate: 5.29,
    effectiveRate: 5.45,
    type: "annuitet",
    requireMembership: false,
    requirePackage: true,
  },
  {
    id: "3350158",
    bankId: "376",
    name: "Grønt Bustadlån",
    nominalRate: 5.29,
    effectiveRate: 5.45,
    type: "annuitet",
    requireMembership: false,
    requirePackage: true,
  },
  {
    id: "3806806",
    bankId: "296648",
    name: "Førstehjemslån",
    nominalRate: 5.29,
    effectiveRate: 5.45,
    type: "annuitet",
    requireMembership: false,
    requirePackage: true,
  },
  {
    id: "3806812",
    bankId: "296648",
    name: "Grønt Rehabiliteringslån",
    nominalRate: 5.29,
    effectiveRate: 5.45,
    type: "annuitet",
    requireMembership: false,
    requirePackage: true,
  },
  {
    id: "3761787",
    bankId: "441",
    name: "LOfavør Grønt Boliglån",
    nominalRate: 5.29,
    effectiveRate: 5.46,
    type: "annuitet",
    requireMembership: true,
    requirePackage: true,
    union: "LOfavør",
  },
  {
    id: "1422977",
    bankId: "341",
    name: "LOfavør Førstehjemslån",
    nominalRate: 5.29,
    effectiveRate: 5.46,
    type: "annuitet",
    requireMembership: true,
    requirePackage: false,
    union: "LOFavør",
  },
  {
    id: "3869518",
    bankId: "342",
    name: "TOBB førstehjemslån",
    nominalRate: 5.29,
    effectiveRate: 5.46,
    type: "annuitet",
    requireMembership: true,
    requirePackage: true,
    union: "TOBB",
  },
  {
    id: "230636",
    bankId: "298",
    name: "BLU - boliglån ungdom",
    nominalRate: 5.3,
    effectiveRate: 5.46,
    type: "annuitet",
    requireMembership: false,
    requirePackage: true,
  },
  {
    id: "2160053",
    bankId: "341",
    name: "Grønt Boliglån",
    nominalRate: 5.29,
    effectiveRate: 5.46,
    type: "annuitet",
    requireMembership: false,
    requirePackage: false,
  },
  {
    id: "2871058",
    bankId: "305",
    name: "Boliglån for unge",
    nominalRate: 5.3,
    effectiveRate: 5.47,
    type: "annuitet",
    requireMembership: false,
    requirePackage: true,
  },
  {
    id: "826456",
    bankId: "305",
    name: "Førstehjemslån 85%",
    nominalRate: 5.3,
    effectiveRate: 5.47,
    type: "annuitet",
    requireMembership: false,
    requirePackage: true,
  },
  {
    id: "1044519",
    bankId: "277",
    name: "Boliglån UNG",
    nominalRate: 5.3,
    effectiveRate: 5.47,
    type: "annuitet",
    requireMembership: false,
    requirePackage: true,
  },
  {
    id: "925206",
    bankId: "352",
    name: "Boliglån Ung",
    nominalRate: 5.3,
    effectiveRate: 5.47,
    type: "annuitet",
    requireMembership: false,
    requirePackage: true,
  },
  {
    id: "1471321",
    bankId: "345",
    name: "LOfavør førstehjemslån",
    nominalRate: 5.3,
    effectiveRate: 5.47,
    type: "annuitet",
    requireMembership: true,
    requirePackage: true,
    union: "LOFavør",
  },
  {
    id: "726652",
    bankId: "357",
    name: "OBOS Nyboliglån",
    nominalRate: 5.32,
    effectiveRate: 5.47,
    type: "annuitet",
    requireMembership: true,
    requirePackage: true,
    union: "Medlemsskap i OBOS",
  },
  {
    id: "2224081",
    bankId: "285",
    name: "Grønt boliglån",
    nominalRate: 5.3,
    effectiveRate: 5.48,
    type: "annuitet",
    requireMembership: false,
    requirePackage: true,
  },
  {
    id: "1436137",
    bankId: "431",
    name: "Boliglån Ung",
    nominalRate: 5.35,
    effectiveRate: 5.48,
    type: "annuitet",
    requireMembership: false,
    requirePackage: false,
  },
  {
    id: "229379",
    bankId: "431",
    name: "Førstehjemslån",
    nominalRate: 5.35,
    effectiveRate: 5.48,
    type: "annuitet",
    requireMembership: false,
    requirePackage: false,
  },
  {
    id: "652376",
    bankId: "342",
    name: "LOfavør Boliglån Ung 34 år",
    nominalRate: 5.34,
    effectiveRate: 5.5,
    type: "annuitet",
    requireMembership: true,
    requirePackage: true,
    union: "LOfavør UNG",
  },
  {
    id: "3286546",
    bankId: "420",
    name: "Førstehjemslån",
    nominalRate: 5.33,
    effectiveRate: 5.51,
    type: "annuitet",
    requireMembership: false,
    requirePackage: false,
  },
  {
    id: "3712109",
    bankId: "346",
    name: "Grønt Førstehjemslån",
    nominalRate: 5.34,
    effectiveRate: 5.51,
    type: "annuitet",
    requireMembership: false,
    requirePackage: false,
  },
  {
    id: "3771442",
    bankId: "346",
    name: "LOfavør Grønt Boliglån",
    nominalRate: 5.34,
    effectiveRate: 5.51,
    type: "annuitet",
    requireMembership: true,
    requirePackage: false,
    union: "LOFavør",
  },
  {
    id: "3488725",
    bankId: "441",
    name: "Grønt boliglån for unge",
    nominalRate: 5.34,
    effectiveRate: 5.51,
    type: "annuitet",
    requireMembership: false,
    requirePackage: true,
  },
  {
    id: "3488727",
    bankId: "441",
    name: "Grønt førstehjemslån",
    nominalRate: 5.34,
    effectiveRate: 5.51,
    type: "annuitet",
    requireMembership: false,
    requirePackage: true,
  },
  {
    id: "2810148",
    bankId: "441",
    name: "LOfavør Førstehjemslån",
    nominalRate: 5.34,
    effectiveRate: 5.51,
    type: "annuitet",
    requireMembership: true,
    requirePackage: true,
    union: "LOfavør",
  },
  {
    id: "826924",
    bankId: "340",
    name: "LOfavør Boliglån for Unge",
    nominalRate: 5.35,
    effectiveRate: 5.51,
    type: "annuitet",
    requireMembership: true,
    requirePackage: true,
    union: "LOfavør UNG, LOFavør",
  },
  {
    id: "3703437",
    bankId: "428",
    name: "Grønt boliglån",
    nominalRate: 5.34,
    effectiveRate: 5.51,
    type: "annuitet",
    requireMembership: false,
    requirePackage: true,
  },
  {
    id: "3762746",
    bankId: "259",
    name: "Grønt lån LOfavør",
    nominalRate: 5.34,
    effectiveRate: 5.52,
    type: "annuitet",
    requireMembership: true,
    requirePackage: true,
    union: "LOfavør",
  },
  {
    id: "2255846",
    bankId: "259",
    name: "LOfavør boliglån for unge",
    nominalRate: 5.34,
    effectiveRate: 5.52,
    type: "annuitet",
    requireMembership: true,
    requirePackage: true,
    union: "LOfavør Ung",
  },
  {
    id: "320355",
    bankId: "332",
    name: "Bustadlån Ung 18-34 år innanfor 90 %, Sogn Sparebank",
    nominalRate: 5.35,
    effectiveRate: 5.52,
    type: "annuitet",
    requireMembership: false,
    requirePackage: false,
  },
  {
    id: "156492",
    bankId: "370",
    name: "BLU - Boliglån for unge",
    nominalRate: 5.35,
    effectiveRate: 5.52,
    type: "annuitet",
    requireMembership: false,
    requirePackage: true,
  },
  {
    id: "3114881",
    bankId: "345",
    name: "Førstehjemslån",
    nominalRate: 5.35,
    effectiveRate: 5.53,
    type: "annuitet",
    requireMembership: false,
    requirePackage: true,
  },
  {
    id: "539034",
    bankId: "345",
    name: "LOfavør Boliglån Ung",
    nominalRate: 5.35,
    effectiveRate: 5.53,
    type: "annuitet",
    requireMembership: true,
    requirePackage: true,
    union: "LOfavør UNG",
  },
  {
    id: "3761778",
    bankId: "345",
    name: "LOfavør Grønt boliglån",
    nominalRate: 5.35,
    effectiveRate: 5.53,
    type: "annuitet",
    requireMembership: true,
    requirePackage: true,
    union: "LOFavør",
  },
  {
    id: "934147",
    bankId: "341",
    name: "LOfavør Boliglån Ung",
    nominalRate: 5.37,
    effectiveRate: 5.54,
    type: "annuitet",
    requireMembership: true,
    requirePackage: false,
    union: "LOfavør Ung",
  },
  {
    id: "3761816",
    bankId: "341",
    name: "LOfavør Miljølån",
    nominalRate: 5.37,
    effectiveRate: 5.54,
    type: "annuitet",
    requireMembership: true,
    requirePackage: false,
    union: "LOFavør",
  },
  {
    id: "46687",
    bankId: "297",
    name: "Bustadlån for unge",
    nominalRate: 5.39,
    effectiveRate: 5.56,
    type: "annuitet",
    requireMembership: false,
    requirePackage: true,
  },
  {
    id: "3351261",
    bankId: "297",
    name: "Grønt bustadlån",
    nominalRate: 5.39,
    effectiveRate: 5.56,
    type: "annuitet",
    requireMembership: false,
    requirePackage: true,
  },
  {
    id: "3747019",
    bankId: "250",
    name: "Akademikerne Pluss Boliglån ung",
    nominalRate: 5.4,
    effectiveRate: 5.56,
    type: "annuitet",
    requireMembership: true,
    requirePackage: true,
    union: "Akademiker Pluss",
  },
  {
    id: "3747039",
    bankId: "250",
    name: "Tekna Boliglån ung",
    nominalRate: 5.4,
    effectiveRate: 5.56,
    type: "annuitet",
    requireMembership: true,
    requirePackage: true,
    union: "Tekna",
  },
  {
    id: "462806",
    bankId: "296648",
    name: "Boliglån for unge",
    nominalRate: 5.39,
    effectiveRate: 5.56,
    type: "annuitet",
    requireMembership: false,
    requirePackage: true,
  },
  {
    id: "951064",
    bankId: "346",
    name: "LOfavør Boliglån Ung",
    nominalRate: 5.39,
    effectiveRate: 5.56,
    type: "annuitet",
    requireMembership: true,
    requirePackage: false,
    union: "LOfavør UNG",
  },
  {
    id: "3792517",
    bankId: "420",
    name: "Grønt boliglån ung",
    nominalRate: 5.39,
    effectiveRate: 5.56,
    type: "annuitet",
    requireMembership: false,
    requirePackage: false,
  },
  {
    id: "3869523",
    bankId: "342",
    name: "TOBB boliglån for unge",
    nominalRate: 5.39,
    effectiveRate: 5.56,
    type: "annuitet",
    requireMembership: true,
    requirePackage: true,
    union: "TOBB",
  },
  {
    id: "630264",
    bankId: "471",
    name: "Boliglån for unge",
    nominalRate: 5.4,
    effectiveRate: 5.57,
    type: "annuitet",
    requireMembership: false,
    requirePackage: false,
  },
  {
    id: "2545457",
    bankId: "422",
    name: "Grønt boliglån",
    nominalRate: 5.39,
    effectiveRate: 5.57,
    type: "annuitet",
    requireMembership: false,
    requirePackage: false,
  },
  {
    id: "1107609",
    bankId: "422",
    name: "Møre Ung Førstehjemslån",
    nominalRate: 5.39,
    effectiveRate: 5.57,
    type: "annuitet",
    requireMembership: false,
    requirePackage: false,
  },
  {
    id: "2160056",
    bankId: "341",
    name: "Grønt Miljølån",
    nominalRate: 5.39,
    effectiveRate: 5.57,
    type: "annuitet",
    requireMembership: false,
    requirePackage: false,
  },
  {
    id: "3862699",
    bankId: "329",
    name: "Grønt boliglån, første bolig",
    nominalRate: 5.39,
    effectiveRate: 5.58,
    type: "annuitet",
    requireMembership: false,
    requirePackage: true,
  },
  {
    id: "3791730",
    bankId: "266",
    name: "Grønt boliglån ung",
    nominalRate: 5.4,
    effectiveRate: 5.58,
    type: "annuitet",
    requireMembership: false,
    requirePackage: true,
  },
  {
    id: "1257943",
    bankId: "285",
    name: "Boliglån for ungdom",
    nominalRate: 5.4,
    effectiveRate: 5.59,
    type: "annuitet",
    requireMembership: false,
    requirePackage: true,
  },
  {
    id: "50073",
    bankId: "462",
    name: "Boliglån Ung",
    nominalRate: 5.45,
    effectiveRate: 5.59,
    type: "annuitet",
    requireMembership: false,
    requirePackage: true,
  },
  {
    id: "3862212",
    bankId: "3861836",
    name: "Boliglån mellom 75-85 % belåningsgrad",
    nominalRate: 5.45,
    effectiveRate: 5.59,
    type: "annuitet",
    requireMembership: false,
    requirePackage: false,
  },
  {
    id: "3506708",
    bankId: "371",
    name: "ECONA - Boliglån UNG",
    nominalRate: 5.44,
    effectiveRate: 5.6,
    type: "annuitet",
    requireMembership: true,
    requirePackage: true,
    union: "ECONA Fordelsavtale",
  },
  {
    id: "3506703",
    bankId: "371",
    name: "ECONA - Førstehjemslån u/90 %",
    nominalRate: 5.44,
    effectiveRate: 5.6,
    type: "annuitet",
    requireMembership: true,
    requirePackage: true,
    union: "ECONA Fordelsavtale",
  },
  {
    id: "3093448",
    bankId: "371",
    name: "UNIO - Boliglån Ung u/90 %",
    nominalRate: 5.44,
    effectiveRate: 5.6,
    type: "annuitet",
    requireMembership: true,
    requirePackage: true,
    union: "UNIO medlemsavtale",
  },
  {
    id: "3093548",
    bankId: "371",
    name: "UNIO - Førstehjemslån u/90 %",
    nominalRate: 5.44,
    effectiveRate: 5.6,
    type: "annuitet",
    requireMembership: true,
    requirePackage: true,
    union: "UNIO medlemsavtale",
  },
  {
    id: "3093200",
    bankId: "371",
    name: "YS - Boliglån Ung u/90 %",
    nominalRate: 5.44,
    effectiveRate: 5.6,
    type: "annuitet",
    requireMembership: true,
    requirePackage: true,
    union: "YS Fordelsavtale",
  },
  {
    id: "3093298",
    bankId: "371",
    name: "YS - Førstehjemslån u/90 %",
    nominalRate: 5.44,
    effectiveRate: 5.6,
    type: "annuitet",
    requireMembership: true,
    requirePackage: true,
    union: "YS Fordelsavtale",
  },
  {
    id: "3761854",
    bankId: "340",
    name: "LOfavør Grønt Boliglån 85%",
    nominalRate: 5.44,
    effectiveRate: 5.6,
    type: "annuitet",
    requireMembership: true,
    requirePackage: true,
    union: "LOFavør",
  },
  {
    id: "3860597",
    bankId: "371",
    name: "Farmaceutene - Boliglån Ung u/90%",
    nominalRate: 5.44,
    effectiveRate: 5.61,
    type: "annuitet",
    requireMembership: true,
    requirePackage: true,
    union: "Farmaceutene",
  },
  {
    id: "3860603",
    bankId: "371",
    name: "Farmaceutene - Førstehjemslån u/90%",
    nominalRate: 5.44,
    effectiveRate: 5.61,
    type: "annuitet",
    requireMembership: true,
    requirePackage: true,
    union: "Farmaceutene",
  },
  {
    id: "3863035",
    bankId: "371",
    name: "Finansforbundet - Boliglån Ung u/90%",
    nominalRate: 5.44,
    effectiveRate: 5.61,
    type: "annuitet",
    requireMembership: true,
    requirePackage: true,
    union: "Finansforbundet Fordelsavtale",
  },
  {
    id: "3863030",
    bankId: "371",
    name: "Finansforbundet - Førstehjemslån u/90%",
    nominalRate: 5.44,
    effectiveRate: 5.61,
    type: "annuitet",
    requireMembership: true,
    requirePackage: true,
    union: "Finansforbundet Fordelsavtale",
  },
  {
    id: "3860580",
    bankId: "371",
    name: "Lederne - Boliglån Ung u/90%",
    nominalRate: 5.44,
    effectiveRate: 5.61,
    type: "annuitet",
    requireMembership: true,
    requirePackage: true,
    union: "Lederne Fordelsavtale",
  },
  {
    id: "3860585",
    bankId: "371",
    name: "Lederne - Førstehjemslån u/90%",
    nominalRate: 5.44,
    effectiveRate: 5.61,
    type: "annuitet",
    requireMembership: true,
    requirePackage: true,
    union: "Lederne Fordelsavtale",
  },
  {
    id: "3708450",
    bankId: "371",
    name: "NITO - Boliglån Ung u/90%",
    nominalRate: 5.44,
    effectiveRate: 5.61,
    type: "annuitet",
    requireMembership: true,
    requirePackage: true,
    union: "NITO Fordelsavtale",
  },
  {
    id: "3708461",
    bankId: "371",
    name: "NITO - Førstehjemslån u/90%",
    nominalRate: 5.44,
    effectiveRate: 5.61,
    type: "annuitet",
    requireMembership: true,
    requirePackage: true,
    union: "NITO Fordelsavtale",
  },
  {
    id: "3860618",
    bankId: "371",
    name: "Norsk Journalistlag (NJ) - Førstehjemslån u/90%",
    nominalRate: 5.44,
    effectiveRate: 5.61,
    type: "annuitet",
    requireMembership: true,
    requirePackage: true,
    union: "Norsk Journalistlag Fordelsavtale",
  },
  {
    id: "3860612",
    bankId: "371",
    name: "Norsk Journalistlag (NJ) - Ung u/90%",
    nominalRate: 5.44,
    effectiveRate: 5.61,
    type: "annuitet",
    requireMembership: true,
    requirePackage: true,
    union: "Norsk Journalistlag Fordelsavtale",
  },
  {
    id: "1102855",
    bankId: "772261",
    name: "Boliglån Ung",
    nominalRate: 5.44,
    effectiveRate: 5.61,
    type: "annuitet",
    requireMembership: true,
    requirePackage: true,
    union: "Norsk Sykepleieforbund",
  },
  {
    id: "2357010",
    bankId: "772261",
    name: "Førstehjemslån",
    nominalRate: 5.44,
    effectiveRate: 5.61,
    type: "annuitet",
    requireMembership: true,
    requirePackage: true,
    union: "Norsk Sykepleieforbund",
  },
  {
    id: "3712121",
    bankId: "346",
    name: "Grønt boliglån for unge",
    nominalRate: 5.44,
    effectiveRate: 5.61,
    type: "annuitet",
    requireMembership: false,
    requirePackage: false,
  },
  {
    id: "1745591",
    bankId: "371",
    name: "Grønt Boliglån",
    nominalRate: 5.54,
    effectiveRate: 5.61,
    type: "annuitet",
    requireMembership: false,
    requirePackage: true,
  },
  {
    id: "2254011",
    bankId: "342",
    name: "Grønt boliglån for unge",
    nominalRate: 5.44,
    effectiveRate: 5.62,
    type: "annuitet",
    requireMembership: false,
    requirePackage: true,
  },
  {
    id: "2253997",
    bankId: "342",
    name: "Grønt førstehjemslån",
    nominalRate: 5.44,
    effectiveRate: 5.62,
    type: "annuitet",
    requireMembership: false,
    requirePackage: true,
  },
  {
    id: "3133341",
    bankId: "346",
    name: "Grønt boliglån",
    nominalRate: 5.44,
    effectiveRate: 5.62,
    type: "annuitet",
    requireMembership: false,
    requirePackage: false,
  },
  {
    id: "465093",
    bankId: "422",
    name: "Møre Ung Boliglån",
    nominalRate: 5.44,
    effectiveRate: 5.62,
    type: "annuitet",
    requireMembership: false,
    requirePackage: false,
  },
  {
    id: "3371389",
    bankId: "306",
    name: "Ungdomslån",
    nominalRate: 5.45,
    effectiveRate: 5.62,
    type: "annuitet",
    requireMembership: false,
    requirePackage: true,
  },
  {
    id: "2923445",
    bankId: "277",
    name: "Boliglån Grønt",
    nominalRate: 5.45,
    effectiveRate: 5.63,
    type: "annuitet",
    requireMembership: false,
    requirePackage: true,
  },
  {
    id: "472199",
    bankId: "357",
    name: "Boliglån Ung",
    nominalRate: 5.47,
    effectiveRate: 5.63,
    type: "annuitet",
    requireMembership: true,
    requirePackage: true,
    union: "Medlemsskap i OBOS",
  },
  {
    id: "46419",
    bankId: "266",
    name: "Boliglån ung",
    nominalRate: 5.45,
    effectiveRate: 5.64,
    type: "annuitet",
    requireMembership: false,
    requirePackage: true,
  },
  {
    id: "3679529",
    bankId: "420",
    name: "NBBO Boliglån ung",
    nominalRate: 5.47,
    effectiveRate: 5.64,
    type: "annuitet",
    requireMembership: true,
    requirePackage: false,
    union: "NBBO - Nedre Buskerud Boligbyggelag",
  },
  {
    id: "3831596",
    bankId: "3831530",
    name: "Boliglån Ung",
    nominalRate: 5.48,
    effectiveRate: 5.65,
    type: "annuitet",
    requireMembership: true,
    requirePackage: true,
    union: "BONORD",
  },
  {
    id: "3831640",
    bankId: "3831530",
    name: "Førstehjemslån",
    nominalRate: 5.48,
    effectiveRate: 5.65,
    type: "annuitet",
    requireMembership: true,
    requirePackage: true,
    union: "BONORD",
  },
  {
    id: "3831735",
    bankId: "3831529",
    name: "Boliglån Ung",
    nominalRate: 5.48,
    effectiveRate: 5.65,
    type: "annuitet",
    requireMembership: true,
    requirePackage: true,
    union: "NOBL",
  },
  {
    id: "3831755",
    bankId: "3831529",
    name: "Førstehjemslån",
    nominalRate: 5.48,
    effectiveRate: 5.65,
    type: "annuitet",
    requireMembership: true,
    requirePackage: true,
    union: "NOBL",
  },
  {
    id: "3808928",
    bankId: "1351017",
    name: "Boliglån Ung innenfor 85%",
    nominalRate: 5.51,
    effectiveRate: 5.65,
    type: "annuitet",
    requireMembership: false,
    requirePackage: false,
  },
  {
    id: "3863247",
    bankId: "1351017",
    name: "Boliglån Ung innenfor 90%",
    nominalRate: 5.51,
    effectiveRate: 5.65,
    type: "annuitet",
    requireMembership: false,
    requirePackage: false,
  },
  {
    id: "3831650",
    bankId: "3831530",
    name: "Grønt boliglån",
    nominalRate: 5.49,
    effectiveRate: 5.66,
    type: "annuitet",
    requireMembership: true,
    requirePackage: true,
    union: "BONORD",
  },
  {
    id: "3831772",
    bankId: "3831529",
    name: "Grønt boliglån",
    nominalRate: 5.49,
    effectiveRate: 5.66,
    type: "annuitet",
    requireMembership: true,
    requirePackage: true,
    union: "NOBL",
  },
  {
    id: "3602550",
    bankId: "474",
    name: "Bate - Boliglån Ung",
    nominalRate: 5.49,
    effectiveRate: 5.66,
    type: "annuitet",
    requireMembership: true,
    requirePackage: true,
    union: "Bate",
  },
  {
    id: "3602562",
    bankId: "474",
    name: "Bate - Grønt Boliglån",
    nominalRate: 5.49,
    effectiveRate: 5.66,
    type: "annuitet",
    requireMembership: true,
    requirePackage: true,
    union: "Bate",
  },
  {
    id: "3804447",
    bankId: "272",
    name: "Grønt Boliglån",
    nominalRate: 5.49,
    effectiveRate: 5.66,
    type: "annuitet",
    requireMembership: false,
    requirePackage: true,
  },
  {
    id: "3528434",
    bankId: "346",
    name: "Førstehjemslån",
    nominalRate: 5.49,
    effectiveRate: 5.66,
    type: "annuitet",
    requireMembership: false,
    requirePackage: false,
  },
  {
    id: "2246858",
    bankId: "340",
    name: "Grønt Boliglån",
    nominalRate: 5.49,
    effectiveRate: 5.67,
    type: "annuitet",
    requireMembership: false,
    requirePackage: true,
  },
  {
    id: "1344511",
    bankId: "368",
    name: "Førstehjemslån",
    nominalRate: 5.49,
    effectiveRate: 5.67,
    type: "annuitet",
    requireMembership: false,
    requirePackage: true,
  },
  {
    id: "2253999",
    bankId: "347",
    name: "Boliglån - UNG Røros",
    nominalRate: 5.49,
    effectiveRate: 5.67,
    type: "annuitet",
    requireMembership: false,
    requirePackage: true,
  },
  {
    id: "2802536",
    bankId: "253",
    name: "Grønt boliglån UNG",
    nominalRate: 5.49,
    effectiveRate: 5.67,
    type: "annuitet",
    requireMembership: false,
    requirePackage: true,
  },
  {
    id: "3594027",
    bankId: "252",
    name: "Boliglån Ung",
    nominalRate: 5.49,
    effectiveRate: 5.67,
    type: "annuitet",
    requireMembership: false,
    requirePackage: true,
  },
  {
    id: "1095314",
    bankId: "252",
    name: "Førstehjemslån",
    nominalRate: 5.49,
    effectiveRate: 5.67,
    type: "annuitet",
    requireMembership: false,
    requirePackage: true,
  },
  {
    id: "1260765",
    bankId: "252",
    name: "Grønt boliglån",
    nominalRate: 5.49,
    effectiveRate: 5.67,
    type: "annuitet",
    requireMembership: false,
    requirePackage: true,
  },
  {
    id: "3453480",
    bankId: "252",
    name: "Vennelån",
    nominalRate: 5.49,
    effectiveRate: 5.67,
    type: "annuitet",
    requireMembership: false,
    requirePackage: true,
  },
];
