import { Footer } from "@/components/app-layout/footer";
import { Header } from "@/components/app-layout/header";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ConvexClientProvider } from "@/components/app-layout/convex-client-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <ConvexClientProvider>
            <NuqsAdapter>
              <div className="flex min-h-dvh flex-col">
                <div className="flex min-h-dvh flex-col">
                  <Header />
                  {children}
                </div>
                <Footer />
              </div>
            </NuqsAdapter>
          </ConvexClientProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
